apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  selector:
    app: posts-api-service
  type: NodePort
  ports:
    - name: posts-port
      protocol: TCP
      port: 4000
      targetPort: 4000
